# _config.yml for it-help.tech (San Diego Local Site)

title: "IT Help San Diego – Apple Expert Home Visits – On-Site Mac Support | WiFi & Cybersecurity | DNS Email · Remote Support"
email: "hello@it-help.tech"
description: "San Diego’s Apple-centric IT support for homes & SMBs. 25+ years fixing Mac, WiFi, DNS & Email issues. We fix macOS/iOS glitches, eliminate WiFi dead zones, boost security, and ensure Email delivery (SPF/DKIM/DMARC)—fast on-site & in-home help. Clear answers & discreet service. We solve tech problems—no monthly retainers."
logo: /images/logo.svg
