name: Blog Comment
description: Submit a comment for a blog post
labels: [comment]
body:
  - type: input
    id: page
    attributes:
      label: Blog Post Slug
      description: Enter the slug or URL of the post you are commenting on
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name
      description: Display name to show with your comment
    validations:
      required: true
  - type: textarea
    id: comment
    attributes:
      label: Comment
      description: Your comment (Markdown allowed)
    validations:
      required: true
